language: node_js
node_js:
  - "node"
before_script:
  - npm install
script:
  - node build.js
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: docs
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages
